# KEGG REST API: query/download (academic use only). See kegg.md.

from .kegg_rest import kegg_request, BASE_URL
from .kegg_operations import (
    query_kegg_info,
    download_kegg_info,
    query_kegg_list,
    download_kegg_list,
    query_kegg_find,
    download_kegg_find,
    query_kegg_get,
    download_kegg_get,
    query_kegg_conv,
    download_kegg_conv,
    query_kegg_link,
    download_kegg_link,
    query_kegg_ddi,
    download_kegg_ddi,
    kegg_info,
    kegg_list,
    kegg_find,
    kegg_get,
    kegg_conv,
    kegg_link,
    kegg_ddi,
)

__all__ = [
    "kegg_request",
    "BASE_URL",
    "query_kegg_info",
    "download_kegg_info",
    "query_kegg_list",
    "download_kegg_list",
    "query_kegg_find",
    "download_kegg_find",
    "query_kegg_get",
    "download_kegg_get",
    "query_kegg_conv",
    "download_kegg_conv",
    "query_kegg_link",
    "download_kegg_link",
    "query_kegg_ddi",
    "download_kegg_ddi",
    "kegg_info",
    "kegg_list",
    "kegg_find",
    "kegg_get",
    "kegg_conv",
    "kegg_link",
    "kegg_ddi",
]
